Add ChannelTypesAttribute
Nihlus/Remora.Discord pull request #114
Opened 2021-09-30 03:42 UTC by carlst99

Adds the `ChannelTypesAttribute` to the commands library, allowing channel types to be specified on `IChannel` command parameters, aiding autocomplete. This builds on #107.

```csharp
[Command("channel-type-demo")]
public async Task<IResult> ChannelTypeDemoCommandAsync(
    [ChannelTypes(ChannelType.GuildText, ChannelType.GuildVoice)] IChannel channel)
{
    ...
}
```

2021-09-30 17:07 UTC, Nihlus requested changes

2021-09-30 17:07 UTC, Nihlus commented on Remora.Discord.Commands/Extensions/CommandTreeExtensions.cs
> +        private static Result<Optional<IReadOnlyList<ChannelType>>> CreateChannelTypesOption(
Your formatting is a little off here - look at the related methods for an example of how to properly do it.

2021-09-30 17:07 UTC, Nihlus commented on Remora.Discord.Commands/Extensions/CommandTreeExtensions.cs
> +            if (channelTypesAttribute is not null && parameterType != ApplicationCommandOptionType.Channel)
Use `is` for checks against constant enum values.

2021-09-30 17:07 UTC, Nihlus commented on Samples/SlashCommands/Commands/HttpCatCommands.cs
> +        public Task<IResult> PostChannelHttpCatAsync(
Same formatting issues here.

2021-09-30 19:35 UTC, AraHaan commented
I would like to have it where this same attribute can be used to *also* lock down a command to usable only from a specific channel type (NSFW channels for example when someone explicitly sets them in their settings to be an NSFW channel).

2021-09-30 19:36 UTC, Nihlus commented
> I would like to have it where this same attribute can be used to _also_ lock down a command to usable only from a specific channel type (NSFW channels for example when someone explicitly sets them in their settings to be an NSFW channel).

That's a very different use case, and not appropriate for this attribute.

2021-10-01 17:54 UTC, Nihlus approved these changes

2021-10-01 17:54 UTC, merged