Add FeedbackMessageOptions to expose additional options on feedback messages.
Nihlus/Remora.Discord pull request #115
Opened 2021-09-30 04:45 UTC by carlst99

Added a `FeedbackMessageOptions` record and implemented support for it in the `FeedbackService`. This allows setting the following additional options common to both normal and interaction response messages when using the `FeedbackService`:

- `IsTTS`
- `File`
- `AllowedMentions`
- `MessageComponents`

There is a slight breaking change in that existing consumers of some methods will need to explicitly name the cancellation token parameter, e.g.

```csharp
-- SendContextualEmbedAsync(Embed embed, CancellationToken ct = default)
-- await SendContextualEmbedAsync(embed, ct);

++ SendContextualEmbedAsync(Embed embed, FeedbackMessageOptions? options = null, CancellationToken ct = default)
++ await SendContextualEmbedAsync(embed, ct: ct);
``

2021-09-30 17:06 UTC, Nihlus requested changes

2021-09-30 17:06 UTC, Nihlus commented on Remora.Discord.Commands/Feedback/Messages/FeedbackMessageOptions.cs
> +    public record FeedbackMessageOptions
Create a primary constructor for this instead - that way, you get more generated useful code.

2021-10-01 17:53 UTC, Nihlus requested changes

2021-10-01 19:15 UTC, carlst99 commented on Remora.Discord.Commands/Feedback/Messages/FeedbackMessageOptions.cs
> +        Optional<bool> IsTTS,
Ah blimey, not sure how I missed that. Sorted!

2021-10-02 09:19 UTC, merged