Add Voice Gateway Object Definitions
Nihlus/Remora.Discord pull request #129
Opened 2021-11-27 09:09 UTC by carlst99

This PR introduces the types used by version four of the voice gateway. It includes the JSON converter (`VoicePayloadConverter`), and all relevant tests.

Some factors to note:

- The `VoiceGatewayCloseStatus.Ratelimited` enum value is undocumented by the API. I chose to include it regardless because ratelimiting needs to be considered, and this OP code should never change (or at least, be reused) for the lifetime of this version of the voice gateway.
- Two event definitions (`IVoiceSpeakingEvent` and `IVoiceClientDisconnect`) have been placed into the unstable library, due to them having an associated OP code but no documented type information.
- The `VoicePayloadConverter` returns a null value, rather than throwing an exception, when it encounters an unknown OP code during deserialization only. This is because the API sends OP codes that have been omitted from the current definitions due to a lack of documentation, and I'd rather the caller handle the null return appropriately than an exception being generated each time this happens.

I additionally changed the `ServiceCollectionExtensions.AddExperimentalDiscordApi(...)` method to accept a name for the `JsonSerializerOptions` object that it configures. This defaults to a value of "Discord" to maintain consistency with the primary configuration point, and ensures that objects in the unstable package can be deserialized without the user having to register them.

Finally, I think I've remembered to use the `var` keyword where appropriate :joy:. Famous last words...

2021-11-27 16:12 UTC, Nihlus commented
Adding this link to the WIP unified gateway as well, since this will hopefully be part of the eventual voice implementation: https://github.com/JakenVeina/DiscordGateway

2021-11-27 16:18 UTC, Nihlus requested changes
This looks great! I'd like you to run the data scrubber against your new sample files before I merge, though, since some IDs can be considered sensitive data.

2021-11-27 16:18 UTC, Nihlus commented on Backend/Remora.Discord.API.Abstractions/API/VoiceGateway/Events/IVoiceReady.cs
> +    string IP { get; }
This could probably be implemented with `IPAddress` from System.Net (https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress?view=net-6.0)

2021-11-27 16:18 UTC, Nihlus commented on Backend/Remora.Discord.Unstable/Unstable/Extensions/ServiceCollectionExtensions.cs
> +                jsonOptions.Converters.Add(new UnstableVoicePayloadConverter());
You can use the extension method `AddConverter` for this - it'll insert it before all other converters in the list, ensuring it takes priority over existing ones.

2021-11-28 00:48 UTC, carlst99 commented
Thanks - scrubber has been run and review resolved.

2021-11-28 09:56 UTC, Nihlus approved these changes

2021-11-28 09:56 UTC, merged