Modal support
Nihlus/Remora.Discord pull request #156
Opened 2022-02-09 00:37 UTC by VelvetThePanda

https://github.com/discord/discord-api-docs/commit/9a86255edba4ce88e6a3f9f928fd14ec5d0097e0

- [x] Basic object support
- [ ] Inbound interaction type
- [ ] API Tests

2022-02-13 13:09 UTC, Nihlus requested changes
Thanks! The PR isn't up to date with the public documentation provided by Discord, so you'll need to do a pass over this one. Please correct the compilation errors as well ;)

2022-02-13 13:09 UTC, Nihlus commented on Backend/Remora.Discord.API/API/Objects/Interactions/Components/Component.cs
> +    Optional<int> MinimumLength,
These should be "MinLength" and "MaxLength" to match the docs.

2022-02-13 17:25 UTC, Nihlus requested changes

2022-02-13 17:25 UTC, Nihlus commented on Backend/Remora.Discord.API.Abstractions/API/Objects/Interactions/Components/Modal/IModalComponent.cs
> +/// Represents a modal component with one or more component fields.
This still references a modal as a component of some kind - please correct that.

2022-02-14 07:09 UTC, VelvetThePanda commented
@Nihlus round two of review 😄 | I'll have to investigate why those tests are failing (I did change something with the converter as per your request if memory serves, but I think I may have broken something there)

2022-02-14 17:23 UTC, merged