Add ANSI formatting string builder
Nihlus/Remora.Discord pull request #190
Opened 2022-05-01 22:57 UTC by MazeXP

Provides a class to build an ANSI formatted string that is supported by Discords ANSI code blocks.

**Example**
![Sample - Dark](https://cdn.discordapp.com/attachments/969719577334415420/969720848317562910/unknown.png)

**Implementation**
The implementation of the build builds the string as in this gist:  [here](https://gist.github.com/MazeXP/617fcf7c8d632cfbf3a7376753df6307#file-6-preview-md)
The class is used like this: [here](https://gist.github.com/MazeXP/617fcf7c8d632cfbf3a7376753df6307#file-5-sample-cs)

**ToDos**
- [ ] Better names for colors especially background colors
- [ ] Tests

**Discussion**
I am open to have a discussion about this implementation and also open for suggestions.  
We should also discuss how we should name the colors properly as the names of the solarized palette are not really user-friendly.

2022-05-03 16:39 UTC, Nihlus commented
Thanks!

Since they're using Solarized as-is, keeping the names in line with their naming is fine.

This has a lot of overlap with the formatting helpers - perhaps the two can be merged somehow?

2022-05-03 16:46 UTC, MazeXP commented
I could think of some call like this from the `Markdown` helper:

## Example
```cs
Markdown.Ansi(b => b.Bold("...").Append("Text"))
```

2022-05-03 18:32 UTC, Tylertron1998 commented
Is there any way to have this be able to be used via static helper methods; something akin to:
```cs
var greenYes = Markdown.GreenForeground("yes");
var redNo = Markdown.RedForeground("no");
```

as having an entire builder for very small usages is a little verbose, imo. I think the builder is absolutely great for larger sections of formatted text. To avoid code duplication, you could just use the `Markdown` class in the builder itself.

Would also make for some nice mixed results with a static using; like:

```cs
var text = OrangeBackground(RedForeground("red on orange"));
```

2022-05-03 19:17 UTC, MazeXP commented
It is to note that the ANSI codes can only be used inside an ANSI code block:
````
```ansi
\u001b[1mBold
...
```
````

Therefore I think it would not be good to expose them directly inside the `Markdown` Class.
They might be better placed in some `Ansi` class.

2022-05-03 19:34 UTC, Tylertron1998 commented
That's a great shout; probably a much better idea in it's own class. Good catch.

2022-05-04 15:40 UTC, MazeXP commented
I could also think of an implementation like in Crayon: https://github.com/riezebosch/crayon

2022-05-10 16:13 UTC, Nihlus requested changes

2022-05-10 17:00 UTC, MazeXP commented on Remora.Discord.Extensions/Formatting/AnsiStringBuilder.cs
> +            IsBold = false;
Just out of interest, what is the reason to use `this.` when accessing member properties?
I would assume readability or any technical reason?

2022-05-10 17:01 UTC, Foxtrek64 commented on Remora.Discord.Extensions/Formatting/AnsiStringBuilder.cs
> +            IsBold = false;
It's a style choice. No benefit; just personal preference from Jax.

2022-05-10 17:03 UTC, Nihlus commented on Remora.Discord.Extensions/Formatting/AnsiStringBuilder.cs
> +            IsBold = false;
Readability, mainly - it's the same reason fields are underscore-prefixed. It helps distinguish fields, member properties/events and locals/parameters at a glance without having to consider casing and font differences.

2022-05-10 17:03 UTC, merged