Add a condition for checking if the user has a given permission in the guild in which the command was executed.
Nihlus/Remora.Discord pull request #51
Opened 2021-02-16 10:56 UTC by TraceLD

Added a condition for checking if the user has a given permission in the guild in which the command was executed. This is very useful for commands such as `!ban` etc. Also added a error that is used when a condition is not met.

2021-02-16 18:34 UTC, Nihlus requested changes

2021-02-16 18:34 UTC, Nihlus commented on Remora.Discord.Commands/Conditions/Attributes/RequireUserGuildPermissionAttribute.cs
> +            Permission = permission;
Prefix public member fields and properties with `this.`

2021-02-16 18:34 UTC, Nihlus commented on Remora.Discord.Commands/Conditions/RequireUserGuildPermissionCondition.cs
> +            var everyoneRole = guildRoles.FirstOrDefault(r => r.Name.Equals("@everyone"));
You should probably check for `guild.ID == role.ID` instead - it's a bit more robust in this case.

2021-02-23 00:20 UTC, TraceLD commented
I have applied the suggestions from your code review @Nihlus.

2021-02-23 18:06 UTC, merged